export { default as BlueBtn } from './BlueBtn'
export { default as SwiperComponent } from './SwiperComponent'
export { default as YellowBtn } from './YellowBtn'
export { default as NavbarCombos } from './NavbarCombos'
export { default as CardsCombos } from './CardsCombos'
export { default as PantallaDescarga } from './PantallaDescarga'
