export const PathConstants = {
  INDEX: '/',
  MENU: '/menu',
  PROMOCIONES: '/promociones',
  PROMOCIONES_DELIVERY: '/promociones/delivery-hamburguesas',
  PROMOCIONES_ID: '/promociones/:id',
  CUPONES: '/cupones',
  COMBOS: '/menu/combos',
  COMBOS_ORDERS: '/menu/combos/*',
  HAMBURGUESAS: '/menu/hamburguesas',
  POLLO: '/menu/pollo',
  MENUSALPLATO: '/menu/menus-al-plato',
  LONCHERITAS: '/menu/loncheritas',
  COMPLEMENTOS: '/menu/complementos',
  BEBIDAS: '/menu/bebidas',
  HELADOS: '/menu/helados',
  INKACHIPS: '/menu/inka-chips',
  CART: '/checkout/cart',
  RECOJO:'/ubicacion',
  RECOJO_ID: '/ubicacion/:id',
  BENEFICIOS: '/beneficios',
};
